### ISSUE TITLE
Cannot 'sbt' the project.

### ISSUE THREAD

**Issue by sledorze** [Romastyi/sbt-play-boilerplate-examples#1]
sbt.ResolveException: unresolved dependency: com.github.romastyi#sbt-play-boilerplate;0.0.1-SNAPSHOT: not found

**Comment by sledorze** [comment]
Oh.. that's a sbt version issue I guess, closing for now..

**Comment by Romastyi** [comment]
Hi! That's my fault too. Sbt plugin has not released yet. This will be done on the next week. But you can try it by release plugin locally. 

1. Clone github repo:
`git clone https://github.com/Romastyi/sbt-play-boilerplate.git`

2. Run command to publish locally:
`sbt "project plugin" "^ publishLocal" "project lib" "+ publishLocal" "project api" "+ publishLocal"`

3. Try to import this sbt project again.
